# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Shorturl CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with: 
        node-version: 10.x
    - name: npm install, test
      run: |
        npm install
        npm test 
      env:
        CI: true
    # develop
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.0.9
      env: 
        SSH_PRIVATE_KEY: ${{secrets.ALIYUN}}
        ARGS: "-avz --delete"
        REMOTE_HOST: "47.107.33.40"
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/shorturl/"
